### PR TITLE
Parity Support

### PR DESCRIPTION
**Pull request by tagomaru**
This PR is for parity support.
It needs to change the repos priv-testnet, polyswarmd, relay, and contractor as well.
The rest will be changed soon.

Please NOTE this is still WIP.

To run parity, please use `base-parity.yml` instead of `base.yml`.
I do not think this is good ides, though.

### CODE REVIEW

**Comment by tagomaru** [comment]
> I believe this will break existing documentation. We should not remove sidechain from base.yml until after a period of deprecation (and updated documentation)

Ah ok, I did not know service could be overwritten on other yaml file.
I deleted `base-parity` and added service of sidechain with geth to `base.yml`.

Thx

**Comment by myhndl** [comment]
@Rizato does this look good to you? Could you give it a run? 

From a skim, it seems to implement the recent discussion in Slack.

**Comment by tagomaru** [comment]
Hi somebody checking this?
If some change is needed, pls let me know, thx!

**Comment by Rizato** [comment]
I think we just need to get polyswarm/geth and polyswarm/parity into CI so these images exist on docker hub

**Pull request merged**
